### ISSUE TITLE
Move action to post hook

### ISSUE THREAD

**Issue by yoramdelangen** [appsfortableau/github-action-releaser#3]
It would be useful to move the "main" action state like uploading to assets into the "post" state.

Why? Because we could use the OUTPUT information like VERSION information from this package and use it within your action.

**current way**.  
```yaml
- name: Set version number
  id: env
  run: |
    SIMPLE_SHA=$(git rev-parse --short ${{ github.sha }})
    LATEST_TAG=$(git describe --tags --match "[0-9]*.[0-9]*.[0-9]*" --abbrev=0 | awk -F \. 'BEGIN {OFS="."} {print $1,$2}' FS=".")
    echo "::set-output name=VERSION::$LATEST_TAG-alpha-$SIMPLE_SHA"
    echo "::set-output name=VERSION_TAG::$LATEST_TAG-alpha"
    # echo "::set-output name=VERSION_BRANCH::$LATEST_TAG-${{ github.ref_name }}-$SIMPLE_SHA"

- name: Create a version number to show in the management console
  run: echo "${{ steps.env.outputs.VERSION }}" > dist/VERSION

- ..... other steps here we can use `${{ steps.env.outputs.VERSION }}`

- name: Upload files and start tagging
  uses: appsfortableau/github-action-releaser@v1
  with:
    tag_name: '${{ steps.env.outputs.VERSION_TAG }}'
    files: ./*.zip
    move_tag: true
    prerelease: true
```

This could be made easy by moving the `Set version number` and/or `Create a version number to show in the management console` into the action and making those variables accessible and uploading the files in the `post` action of the job.

```yaml
- name: Upload files and start tagging
  uses: appsfortableau/github-action-releaser@v1
  id: env
  with:
    tag_name: '${{ steps.env.outputs.VERSION_TAG }}'
    files: ./*.zip
    move_tag: true
    prerelease: true

- ..... other steps here we can use `${{ steps.env.outputs.VERSION }}`
```
